# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8f31e60af12177bfd48d1aee3aff324d57f513bd32f5994676e2ee808b7dac855f5c80c9adb09ea26261861c99587c0f6a2ed886da980572cd11162a629c45c4

test:
  secret_key_base: 88e03b72a3d8a4c04aaae98e265f167b5694993a34e52024f8e3b80fd84d66af8f41e555ace132f6d6b7a91548c31dc156c5adb5dbeeea38a7800c34e0cb1d5e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
